"""The admin UI stylesheet.

Lifted out of _ui_html.py on 2026-07-28, where 625 lines of one string literal sat between
the page shell and the funnel. It is data, not logic — the same category as _i18n.py's
translation table — and everyone reading that module for a function scrolled past all of
it to reach one.
"""
from __future__ import annotations


def _icons_only_sidebar(sel: str) -> str:
    """The icons-only sidebar — reached ONLY by the collapse button, never by viewport width.

    It hides .sid-ft, and that is where the branch picker, the bot/sending/comment switches and
    the language buttons live. Hiding them is acceptable when a person pressed the button that
    does it and can press it again; it is not acceptable as something a window size decides. A
    width-driven version shipped on 2026-07-28 and was reverted the same day, because the first
    person to open the panel on a phone could not find the switches.

    Kept as a function so the selector is stated once — the parameter is what keeps this honest
    about having exactly one caller."""
    return (
        f"{sel}{{width:48px!important;min-width:48px!important}}"
        f"{sel} .logo,{sel} .na-lbl,{sel} .nav-sep,{sel} .sid-ft,"
        f"{sel} .na-badge,{sel} .na-badge2{{display:none}}"
        f"{sel} .na{{justify-content:center;padding:.4rem 0;margin:.05rem .2rem}}"
        f"{sel} .sid-top{{justify-content:center;padding:.7rem .3rem .45rem}}"
    )


_SIDEBAR_BY_HAND = _icons_only_sidebar(".sid.collapsed")

_CSS = (
    "*{box-sizing:border-box;margin:0;padding:0}"
    # Firefox scrollbar styling (Chromium/Safari use ::-webkit-scrollbar below); keeps every
    # scroll region slim instead of a full-width OS bar in Firefox.
    "*{scrollbar-width:thin;scrollbar-color:rgba(255,255,255,.18) transparent}"
    # overflow-x hidden (no sideways scroll) but overflow-y left OPEN on the root so the
    # browser's OWN pull-to-refresh can fire: the columns are flex/position:fixed at 100%
    # height with inner overflow:auto scrollers, so the document itself never actually
    # scrolls on desktop — but a downward overscroll at the top of a region chains to the
    # document and triggers the native refresh (works in desktop-mode-on-phone too). No JS
    # emulation. Chats open at the newest message (scrollAllBot/pinBot), so the feed is
    # never sitting at the top where an accidental pull could fire.
    "html,body{height:100%;overflow-x:hidden}"
    "body{display:flex;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;"
    "background:#0f1117;color:#d0d7de;font-size:14px}"
    # Structural link style — theme accent, no browser-default blue/underline. Anything more
    # specific (.na, .ti, .sn, message-bubble links, etc.) overrides this via normal cascade
    # order/specificity; this is only the inherited fallback so a bare <a> never falls back to
    # UA-agent blue.
    "a{color:#4da6ff;text-decoration:none}"
    "a:hover{text-decoration:underline}"
    # coach 'thinking' indicator — shown only while the htmx request is in flight
    ".coach-think{display:none;align-items:center;gap:.5rem;padding:.35rem .85rem;"
    "font-size:.78rem;color:#8899aa;flex-shrink:0}"
    ".htmx-request.coach-think{display:flex}"
    ".spin{width:.9rem;height:.9rem;border:2px solid #2d3748;border-top-color:#4da6ff;"
    "border-radius:50%;display:inline-block;animation:spin .7s linear infinite;flex-shrink:0}"
    "@keyframes spin{to{transform:rotate(360deg)}}"
    ".sid{width:210px;flex-shrink:0;background:#141925;border-right:1px solid #2d3748;"
    "display:flex;flex-direction:column;transition:width .15s}"
    ".sid-top{padding:.7rem .9rem .45rem;border-bottom:1px solid #2d3748;"
    "display:flex;align-items:center;justify-content:space-between}"
    ".logo{font-size:1.05rem;font-weight:800;color:#fff}"
    ".sid-nav{flex:1;padding:.4rem 0;overflow-y:auto;overflow-x:hidden}"
    ".na{display:flex;align-items:center;gap:.5rem;padding:.4rem .75rem;color:#8899aa;"
    "font-size:.81rem;text-decoration:none;border-radius:6px;margin:.05rem .45rem;"
    "transition:background .12s,color .12s;cursor:pointer;white-space:nowrap;overflow:hidden}"
    ".na:hover{background:rgba(255,255,255,.08);color:#d0d7de}"
    ".na.on{background:rgba(32,107,196,.22);color:#4da6ff}"
    ".na i{width:14px;text-align:center;flex-shrink:0}"
    ".na-lbl{overflow:hidden;text-overflow:ellipsis}"
    ".na-badge{margin-left:auto;padding:.05rem .45rem;border-radius:8px;font-size:.7rem;"
    "font-weight:700;background:#206bc4;color:#fff;flex-shrink:0}"
    ".na-badge:empty{display:none}"
    # Inbox two-number badge: in-queue pill (orange) + won't-reply pill (grey), sum = unanswered
    ".na-badge2{margin-left:auto;display:flex;gap:3px;flex-shrink:0}"
    ".na-badge2:empty{display:none}"
    ".iaw{padding:.05rem .4rem;border-radius:8px;font-size:.7rem;font-weight:700;color:#fff;"
    "cursor:pointer}"
    ".iaw-q{background:#e8590c}"    # in generation queue — Stepan will reply
    ".iaw-off{background:#6b7685}"  # kept: the ?awaiting=off list still labels its rows
    ".nav-sep{height:1px;background:#2d3748;margin:.4rem .9rem}"
    ".sid-ft{padding:.55rem .7rem .7rem;border-top:1px solid #2d3748}"
    ".lrow{display:flex;gap:.22rem;margin-top:.3rem}"
    ".lb{flex:1;padding:.22rem .1rem;background:rgba(255,255,255,.07);"
    "border:1px solid rgba(255,255,255,.12);border-radius:4px;color:#8899aa;"
    "font-size:.68rem;font-weight:600;text-align:center;text-decoration:none}"
    ".lb.on,.lb:hover{background:rgba(32,107,196,.28);color:#4da6ff;border-color:#206bc4}"
    ".bft-lbl{font-size:.63rem;color:#4a5568;margin-bottom:.2rem}"
    ".bft-sel{width:100%;background:#1a1f2e;border:1px solid #2d3748;border-radius:4px;"
    "color:#d0d7de;font-size:.72rem;padding:.22rem .35rem;cursor:pointer}"
    # sidebar collapse
    ".sb-col{background:none;border:none;color:#4a5568;cursor:pointer;font-size:.9rem;"
    "padding:.1rem .25rem;line-height:1;flex-shrink:0}"
    ".sb-col:hover{color:#d0d7de}"
    f"{_SIDEBAR_BY_HAND}"
    # sidebar + thread resize handles
    ".sbrz,.thrz{width:4px;flex-shrink:0;background:#1e2636;cursor:col-resize;"
    "transition:background .15s;z-index:10}"
    ".sbrz:hover,.sbrz.drag,.thrz:hover,.thrz.drag{background:#206bc4}"
    ".thr{width:305px;flex-shrink:0;background:#0f1117;border-right:1px solid #2d3748;"
    "display:flex;flex-direction:column;overflow:hidden}"
    ".thr-h{padding:.56rem .8rem;border-bottom:1px solid #2d3748;font-size:.82rem;"
    "font-weight:600;color:#e8eef4;flex-shrink:0;display:flex;align-items:center;gap:.5rem}"
    ".chk-kinds{display:flex;gap:.3rem;margin-left:auto}"
    ".chk-kind{background:none;border:1px solid #2d3748;border-radius:5px;padding:.15rem .4rem;"
    "cursor:pointer;font-size:.82rem;line-height:1}"
    ".chk-kind.on{border-color:#3a4759}"
    # 'off' = this source is filtered out: dim ONLY the icon (opacity on the button would fade
    # the strike line too) and draw a crisp centred strikethrough over it.
    ".chk-kind.off{position:relative}"
    ".chk-kind.off i{opacity:.4}"
    ".chk-kind.off::after{content:'';position:absolute;left:8%;right:8%;top:50%;"
    "border-top:2px solid #c9d3de;transform:translateY(-50%)}"
    ".ad-filter{display:flex;align-items:center;gap:.4rem;padding:.35rem .8rem;flex-shrink:0;"
    "font-size:.68rem;color:#8899aa;background:#1a2230;border-bottom:1px solid #2d3748}"
    ".ad-filter-id{font-family:ui-monospace,monospace;color:#4da6ff;font-size:.64rem}"
    ".ad-filter-x{margin-left:auto;color:#8899aa;text-decoration:none;font-weight:700;"
    "padding:0 .3rem;border-radius:3px}"
    ".ad-filter-x:hover{background:#2d3748;color:#e8eef4}"
    ".ti-q{width:calc(100% - 1rem);margin:.4rem .5rem;padding:.34rem .55rem;flex-shrink:0;"
    "background:#0f1621;border:1px solid #2d3748;border-radius:6px;color:#e8eef4;"
    "font-size:.76rem;outline:none}.ti-q:focus{border-color:#206bc4}"
    "#tl{flex:1;overflow-y:auto}"
    "#tl::-webkit-scrollbar{width:4px}"
    "#tl::-webkit-scrollbar-thumb{background:rgba(255,255,255,.15);border-radius:2px}"
    ".ti{display:flex;align-items:flex-start;gap:.5rem;padding:.52rem .8rem;"
    "border-bottom:1px solid rgba(255,255,255,.04);"
    "text-decoration:none;color:inherit;cursor:pointer;transition:background .1s;"
    "border-left:2px solid transparent}"
    ".ti:hover{background:rgba(255,255,255,.05);text-decoration:none}"
    ".ti.on{background:rgba(32,107,196,.14);border-left-color:#206bc4}"
    ".ti-av{width:32px;height:32px;border-radius:50%;flex-shrink:0;"
    "background-size:cover;background-position:center;"
    "background-color:#2a3550;color:#6b7685;font-size:.78rem;font-weight:700;"
    "display:flex;align-items:center;justify-content:center;margin-top:.06rem}"
    ".ch-av{width:36px;height:36px;border-radius:50%;flex-shrink:0;"
    "background-size:cover;background-position:center;"
    "background-color:#2a3550;color:#6b7685;font-size:.88rem;font-weight:700;"
    "display:flex;align-items:center;justify-content:center}"
    ".ti-body{flex:1;min-width:0;overflow:hidden}"
    ".ti-t{display:flex;align-items:baseline;gap:.35rem;margin-bottom:.1rem}"
    ".ti-n{font-weight:600;color:#e8eef4;font-size:.84rem;flex:1;overflow:hidden;"
    "text-overflow:ellipsis;white-space:nowrap}"
    ".ti-ts{font-size:.68rem;color:#4a5568;flex-shrink:0}"
    ".ti-p{font-size:.74rem;color:#6b7685;overflow:hidden;text-overflow:ellipsis;"
    "white-space:nowrap;margin-top:.05rem}"
    ".ti-handle{font-size:.67rem;color:#4a5568;margin-top:.02rem}"
    ".ti-sub{font-size:.62rem;color:#4a5568;display:flex;gap:.35rem;margin-top:.06rem;"
    "white-space:nowrap;overflow:hidden;align-items:center}"
    ".ti-cnt{opacity:.7}"
    # source bar (lead origin — ad / story / direct)
    ".srcbar{display:flex;align-items:center;gap:.45rem;padding:.22rem .9rem;"
    "background:#0d1017;border-bottom:1px solid #1e2636;font-size:.71rem;flex-shrink:0}"
    ".srclbl{display:inline-flex;align-items:center;gap:.25rem;color:#6b7685}"
    ".src-paid{color:#d6a96f}.src-story{color:#4da6ff}.src-direct{color:#4a5568}"
    ".srcid{font-family:ui-monospace,monospace;font-size:.65rem;color:#4a5568;cursor:pointer;"
    "padding:.1rem .3rem;background:#1a1f2e;border-radius:3px;text-decoration:none}"
    ".srcid:hover{color:#8899aa}"
    ".srcthumb{width:30px;height:30px;border-radius:4px;object-fit:cover;"
    "border:1px solid #2d3748;flex-shrink:0}"
    ".ch-meta{width:100%;font-size:.67rem;color:#4a5568;display:flex;gap:.55rem;"
    "align-items:center;margin-top:.18rem;padding-top:.22rem;"
    "border-top:1px solid #1e2636;flex-wrap:wrap}"
    ".ch-meta a{color:#4a5568;text-decoration:none}"
    ".ch-meta a:hover{color:#8899aa}"
    ".bg{display:inline-block;padding:.07rem .3rem;border-radius:5px;font-size:.6rem;"
    "font-weight:700;text-transform:uppercase;margin-right:.18rem}"
    ".sn{background:#1e3a5f;color:#4da6ff}.snu{background:#3a2a10;color:#d6a96f}"
    ".sq{background:#2a1f5f;color:#9b7aff}"
    ".sp{background:#1f3a2a;color:#4adb7a}.so{background:#3a2a1f;color:#ffa94d}"
    ".sr{background:#1f3a2a;color:#51cf66}.sh{background:#163030;color:#22b8cf}"
    ".sd{background:#2a2a2a;color:#868e96}.sm{background:#3a1f1f;color:#ff6b6b}"
    # two-row funnel: row 1 = headline metrics (total/bot-on/in-funnel, one is non-clickable
    # via .info), row 2 = per-stage + blocked chips. Each row is a compact icon+count step,
    # full label on hover (title).
    ".fnl{display:flex;gap:.15rem;padding:.3rem .5rem;border-bottom:1px solid #1e2636;"
    "flex-shrink:0;align-items:stretch}"
    ".fnl:first-of-type{border-bottom-color:#161b26}"
    ".fstep{flex:1;min-width:0;display:flex;flex-direction:column;align-items:center;"
    "gap:.05rem;padding:.2rem .1rem;border-radius:6px;text-decoration:none;cursor:pointer;"
    "border:1px solid transparent;border-top:2px solid transparent;transition:background .1s}"
    ".fstep:hover{background:#1c2230}"
    ".fstep.on{background:#1e2b40;border-color:#31527a}"
    ".fstep.info{cursor:default}"
    ".fstep.info:hover{background:transparent}"
    ".fst-i{font-size:.82rem;line-height:1}"
    ".fst-n{font-size:.72rem;font-weight:700;color:#c8d6e5}"
    ".fstep.on .fst-n{color:#fff}"
    "._legacy-fnl{font-size:.62rem;color:#4a5568;cursor:pointer;text-decoration:none;"
    "padding:.12rem .3rem;border-radius:3px}"
    # reports panel
    ".kpi-row{display:flex;gap:.6rem;flex-wrap:wrap;margin-bottom:.65rem}"
    # lead-segment tree (svg)
    ".seg-tree{margin:.1rem 0 .7rem;overflow-x:auto}"
    # one-line sales funnel
    ".fnl-line{display:flex;gap:.3rem;align-items:stretch}"
    ".fnl-step{flex:1;min-width:0;background:#141925;border:1px solid #2d3748;"
    "border-radius:6px;padding:.35rem .3rem;text-align:center;position:relative;"
    "overflow:hidden;cursor:help}"
    ".fnl-bar{position:absolute;top:0;left:0;right:0;height:3px}"
    ".fnl-num{font-size:1.05rem;font-weight:800;color:#e8eef4;line-height:1.1;margin-top:.15rem}"
    ".fnl-nm{font-size:.6rem;color:#8899aa;text-transform:capitalize;white-space:nowrap;"
    "overflow:hidden;text-overflow:ellipsis}"
    ".fnl-pct{font-size:.62rem;color:#5a6472;font-weight:700}"
    ".fnl-side-row{display:flex;gap:.35rem;flex-wrap:wrap;margin:.4rem 0 .2rem}"
    ".fnl-side{font-size:.63rem;color:#c3cede;border:1px solid;border-radius:10px;"
    "padding:.05rem .5rem;cursor:help}"
    # report quick-range presets
    ".rep-presets{display:flex;gap:.35rem;flex-wrap:wrap;margin-bottom:.5rem}"
    ".rep-preset{background:#161b26;border:1px solid #2d3748;color:#93a1b3;"
    "border-radius:5px;padding:.25rem .6rem;font-size:.72rem;cursor:pointer;"
    "text-decoration:none;white-space:nowrap}"
    ".rep-preset:hover{border-color:#4da6ff;color:#4da6ff}"
    ".rep-preset.on{background:#206bc4;border-color:#206bc4;color:#fff}"
    # report date-range form
    ".rep-dates{display:flex;gap:.5rem;align-items:flex-end;flex-wrap:wrap;margin-bottom:.7rem}"
    ".rep-dates label{display:flex;flex-direction:column;gap:.15rem;font-size:.63rem;color:#8899aa}"
    ".rep-dates input[type=date]{background:#0f1117;border:1px solid #2d3748;color:#d0d7de;"
    "border-radius:5px;padding:.25rem .4rem;font-size:.72rem;color-scheme:dark}"
    ".rep-dates button{background:#206bc4;color:#fff;border:none;border-radius:5px;"
    "padding:.32rem .7rem;font-size:.72rem;font-weight:600;cursor:pointer}"
    ".rep-dhint{font-size:.6rem;color:#5a6472;font-style:italic;align-self:center}"
    ".kpi{background:#141925;border:1px solid #2d3748;border-radius:6px;"
    "padding:.5rem .75rem;min-width:90px}"
    ".kpi-n{font-size:1.5rem;font-weight:800;line-height:1.15}"
    ".kpi-lnk{display:block;text-decoration:none;cursor:pointer}"
    ".kpi-lnk:hover{border-color:#4a5568;background:#1a212a}"
    ".kpi-l{font-size:.64rem;color:#6b7685;margin-top:.1rem}"
    # Per-day bars under the number. flex-end so bars grow upward from a shared baseline;
    # each <i> carries its own height% and a day:count tooltip.
    ".kpi-spark{display:flex;align-items:flex-end;gap:1px;height:18px;margin-top:.3rem}"
    ".kpi-spark i{flex:1 1 0;min-width:1px;border-radius:1px}"
    ".rep-tbl{width:auto;border-collapse:collapse;font-size:.77rem;margin-bottom:.7rem}"
    ".rep-tbl th{text-align:left;color:#6b7685;font-weight:600;font-size:.65rem;"
    "padding:.25rem .55rem;border-bottom:1px solid #2d3748;white-space:nowrap}"
    ".rep-tbl td{padding:.25rem .55rem;border-bottom:1px solid #1a2033;white-space:nowrap}"
    ".rep-n{text-align:right;font-weight:700;color:#e8eef4}"
    # ad-funnel: sortable headers + per-column filter row
    ".rep-sort{cursor:pointer;user-select:none;white-space:nowrap}"
    ".rep-sort:hover{color:#93a1b3}"
    ".rep-arr{font-size:.6rem;color:#4da6ff}"
    ".rep-fltr th{padding-top:0;padding-bottom:.3rem;border-bottom:1px solid #2d3748}"
    ".rep-f{width:100%;box-sizing:border-box;background:#161b26;border:1px solid #2d3748;"
    "color:#e8eef4;border-radius:3px;font-size:.62rem;padding:.12rem .28rem}"
    ".rep-f::placeholder{color:#4a5568}"
    ".rep-lnk{color:inherit;text-decoration:none}"
    ".rep-lnk:hover{text-decoration:underline}"
    # ad-funnel: click-to-open menu on the ad id, product-mapping select + suggestion chip
    ".admenu{display:inline-block;position:relative}"
    ".admenu>summary{list-style:none;cursor:pointer;color:#4da6ff;"
    "font-family:ui-monospace,monospace;font-size:.7rem}"
    ".admenu>summary::-webkit-details-marker{display:none}"
    ".admenu-pop{position:absolute;z-index:20;top:1.2rem;left:0;background:#1a2230;"
    "border:1px solid #2d3748;border-radius:5px;padding:.25rem;min-width:180px;"
    "box-shadow:0 6px 20px rgba(0,0,0,.4);display:flex;flex-direction:column}"
    ".admenu-pop a{padding:.4rem .55rem;border-radius:4px;color:#e8eef4;text-decoration:none;"
    "font-size:.72rem;white-space:nowrap}"
    ".admenu-pop a:hover{background:#2d3748}"
    ".ad-ig{text-decoration:none;margin-left:.15rem}"
    ".ig-pop{position:fixed;z-index:950;display:none;padding:3px;background:#0d1117;"
    "border:1px solid #2d3748;border-radius:6px;box-shadow:0 8px 24px rgba(0,0,0,.5)}"
    ".ig-pop img{display:block;max-width:200px;max-height:200px;border-radius:4px}"
    ".admap-sel{background:#161b26;border:1px solid #2d3748;color:#e8eef4;border-radius:4px;"
    "padding:.15rem .3rem;font-size:.68rem;max-width:150px}"
    ".admap-sug{background:none;border:1px dashed #4a5568;color:#ffa94d;border-radius:4px;"
    "cursor:pointer;font-size:.64rem;padding:.1rem .35rem;margin-left:.3rem}"
    ".admap-sug:hover{border-color:#ffa94d;background:#26211a}"
    # hourly activity: grouped in/out bars per hour-of-day, faint mid gridline + bottom axis
    ".hchart{display:flex;align-items:flex-end;gap:4px;height:104px;margin-top:.4rem;"
    "border-bottom:1px solid #2d3748;"
    "background-image:linear-gradient(#222a38 1px,transparent 1px);background-size:100% 50%}"
    ".hbar{display:flex;flex-direction:column;align-items:center;flex:1;height:100%;"
    "justify-content:flex-end}"
    ".hbar-g{display:flex;align-items:flex-end;justify-content:center;gap:2px;width:100%;"
    "height:100%}"
    ".hbar-in{width:40%;max-width:11px;background:#4da6ff;border-radius:2px 2px 0 0}"
    ".hbar-out{width:40%;max-width:11px;background:#51cf66;border-radius:2px 2px 0 0}"
    ".hbar:hover .hbar-in,.hbar:hover .hbar-out{filter:brightness(1.3)}"
    ".hbar-l{font-size:.55rem;color:#6b7685;margin-top:3px;line-height:1}"
    # needs cloud — 3-column AI-aggregated tag table, sits to the RIGHT of the funnel
    ".rep-fc{display:flex;gap:1rem;align-items:flex-start;flex-wrap:wrap}"
    ".rep-fc-funnel{flex:1 1 300px;min-width:0}"
    ".ncl-wrap{flex:1 1 320px;min-width:280px}"
    ".ncl-title{font-size:.78rem;color:#8899aa;margin:1rem 0 .4rem}"
    ".ncl-cols{display:flex;gap:.5rem}"
    ".ncl-col{flex:1;min-width:0}"
    ".ncl-hd{font-size:.66rem;font-weight:700;text-transform:uppercase;letter-spacing:.03em;"
    "margin-bottom:.35rem}"
    ".ncl-row{position:relative;display:flex;align-items:center;gap:.35rem;padding:.16rem .3rem;"
    "margin-bottom:2px;border-radius:3px;overflow:hidden;background:rgba(255,255,255,.03)}"
    ".ncl-bar{position:absolute;left:0;top:0;bottom:0;opacity:.22;border-radius:3px;z-index:0}"
    ".ncl-lbl{position:relative;z-index:1;font-size:.66rem;color:#d5dee8;white-space:nowrap;"
    "overflow:hidden;text-overflow:ellipsis;flex:1}"
    ".ncl-n{position:relative;z-index:1;font-size:.62rem;color:#8899aa;font-weight:600}"
    ".ncl-empty{font-size:.62rem;color:#6b7685;padding:.2rem .3rem}"
    # compact mini variant of the activity chart (placed high in the reports panel)
    # Date filter left, hour histogram right; the histogram keeps its own max-width and
    # drops under the dates on a narrow screen rather than squeezing them.
    ".rep-top{display:flex;gap:1rem;align-items:flex-start;flex-wrap:wrap;"
    "justify-content:space-between}"
    ".rep-top-dates{flex:1 1 340px;min-width:0}"
    ".rep-top .mini-act{flex:1 1 420px;margin:0}"
    ".mini-act{margin:.55rem 0 .3rem;max-width:520px}"
    ".mini-act-hd{display:flex;justify-content:space-between;align-items:baseline;gap:.5rem;"
    "flex-wrap:wrap;margin-bottom:.25rem}"
    ".mini-act-t{font-size:.7rem;color:#8899aa;font-weight:600}"
    ".mini-act-s{font-size:.62rem;color:#6b7685}"
    ".hchart-mini{height:46px;gap:3px;margin-top:0}"
    ".hchart-mini .hbar-l{font-size:.5rem;margin-top:2px}"
    "#main{flex:1;display:flex;flex-direction:column;overflow:hidden;min-width:0}"
    ".ch{padding:.56rem .9rem;border-bottom:1px solid #2d3748;background:#141925;"
    "display:flex;align-items:center;gap:.55rem;flex-shrink:0;flex-wrap:wrap}"
    ".ch-n{font-weight:600;color:#e8eef4;font-size:.9rem}"
    ".ch-src{font-size:.82rem;margin-left:.15rem}"
    ".ch-sub{font-size:.67rem;color:#4a5568;font-family:monospace}"
    ".msgs{flex:1;overflow-y:auto;padding:.72rem .95rem;display:flex;"
    "flex-direction:column;gap:.3rem}"
    # pending bubbles live inside their own #pend-<tid> wrapper, not directly in .msgs, so
    # their align-self:flex-end needs THIS wrapper to be a flex column too — else they fall
    # back to block layout and render left instead of on the right like a real outgoing msg.
    "[id^='pend-']{display:flex;flex-direction:column;gap:.3rem}"
    ".msgs::-webkit-scrollbar{width:4px}"
    ".msgs::-webkit-scrollbar-thumb{background:rgba(255,255,255,.15);border-radius:2px}"
    ".bb{display:flex;flex-direction:column;max-width:72%}"
    ".bb-i{align-self:flex-start}.bb-o{align-self:flex-end}.bb-p{opacity:.6;align-self:flex-end}"
    ".bb-ex{opacity:.4;filter:grayscale(.7)}"  # cleared: greyed, out of Stepan's context
    ".bb-ex .bt{background:#20242c!important;border:1px dashed #3a4453}"
    ".sys-log{align-self:center;max-width:90%;font-size:.72rem;color:#5a6472;"
    "text-align:center;margin:.3rem 0;font-style:italic}"
    ".delx-pop{display:inline-flex;gap:.2rem;align-items:center;margin-left:.2rem}"
    ".delx-pop button{border:none;border-radius:3px;cursor:pointer;font-size:.7rem;"
    "padding:.02rem .3rem;line-height:1.3}"
    ".delx-y{background:#862e2e;color:#fff}.delx-n{background:#2d3748;color:#c3cede}"
    ".note-pop-bg{position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:40;"
    "animation:notePopBgIn .2s ease-out}"
    ".note-pop{position:fixed;top:30%;left:50%;z-index:41;"
    "background:#181c26;border:1.5px solid #4a8dff;border-radius:12px;padding:.85rem;"
    "width:min(320px,90vw);box-shadow:0 12px 32px rgba(0,0,0,.5),0 0 0 4px rgba(74,141,255,.12),"
    "0 0 22px rgba(74,141,255,.28);"
    "animation-name:notePopIn,notePopFloat;animation-duration:.32s,3.2s;"
    "animation-timing-function:cubic-bezier(.25,1,.4,1),ease-in-out;"
    "animation-delay:0s,.32s;animation-iteration-count:1,infinite;"
    "animation-fill-mode:forwards,none}"
    "@keyframes notePopBgIn{from{opacity:0}to{opacity:1}}"
    "@keyframes notePopIn{from{opacity:0;transform:translate(-50%,10px) scale(.94)}"
    "to{opacity:1;transform:translate(-50%,0) scale(1)}}"
    "@keyframes notePopFloat{0%,100%{transform:translate(-50%,0)}"
    "50%{transform:translate(-50%,-6px)}}"
    "@media (prefers-reduced-motion:reduce){.note-pop,.note-pop-bg{animation:none;"
    "transform:translate(-50%,0)}}"
    ".note-pop-h{font-size:.78rem;color:#c3cede;margin-bottom:.4rem}"
    ".emo-bar{display:flex;flex-wrap:wrap;gap:.15rem;padding:.25rem .1rem 0}"
    ".emo-bar button{background:none;border:none;cursor:pointer;font-size:1.05rem;"
    "line-height:1;padding:.1rem .18rem;border-radius:4px}"
    ".emo-bar button:hover{background:#222836}"
    ".bt{padding:.4rem .56rem;border-radius:9px;font-size:.8rem;"
    "white-space:pre-wrap;word-break:break-word}"
    ".bb-i .bt{background:#232a3b;border:1px solid #2d3748}"
    ".bb-o .bt{background:#1e3a5f}.bb-o.mgr .bt{background:#2a1f3a}"
    ".bb-p .bt{border:1px dashed #3a5578}"  # queued (unsent) look
    ".b-tr{font-size:.75rem;color:#5aa2ff;margin-top:.12rem}.bb-o .b-tr{text-align:right}"
    ".bt.trview{color:#5aa2ff}"
    ".toast{position:fixed;left:50%;bottom:26px;transform:translateX(-50%) translateY(8px);"
    "background:#2a1512;border:1px solid #5a2a20;color:#ffb4a2;padding:.6rem 1rem;"
    "border-radius:10px;font-size:.85rem;z-index:300;opacity:0;pointer-events:none;"
    "max-width:86vw;text-align:center;transition:opacity .2s,transform .2s}"
    ".toast.on{opacity:1;transform:translateX(-50%) translateY(0)}"
    ".bm{font-size:.63rem;color:#4a5568;margin-bottom:.1rem;display:flex;"
    "align-items:center;gap:.2rem}"
    ".bb-o .bm{justify-content:flex-end}"
    ".b-llm{font-size:.63rem;color:#4a5568;margin-top:.2rem;max-width:100%;"
    "font-family:ui-monospace,monospace;letter-spacing:.1px;"
    "white-space:nowrap;overflow:hidden;text-overflow:ellipsis}"
    ".bb-o .b-llm{text-align:right}"
    # per-message translate and delete buttons — hidden until bubble hover
    ".trx,.delx{background:none;border:none;color:#4a5568;cursor:pointer;"
    "font-size:.68rem;padding:0 .1rem;line-height:1;opacity:0;"
    "transition:opacity .12s,color .1s}"
    ".bb:hover .trx,.bb:hover .delx{opacity:.5}"
    ".trx:hover{opacity:1!important;color:#4da6ff}"
    ".delx:hover{opacity:1!important;color:#ff6b6b}"
    ".fin{padding:.45rem .8rem .52rem;border-top:1px solid #2d3748;"
    "background:#141925;flex-shrink:0}"
    ".fin-tools{display:flex;align-items:center;gap:.3rem;margin-bottom:.3rem;overflow-x:auto}"
    ".fin-tools .act-btn{flex-shrink:0}"
    ".fin-tools .emo-bar{flex-wrap:nowrap;flex-shrink:0}"
    ".fin-row{display:flex;gap:.4rem;align-items:flex-end}"
    ".fin textarea{flex:1;background:#1a1f2e;border:1px solid #2d3748;border-radius:6px;"
    "color:#d0d7de;padding:.36rem .52rem;font-size:.8rem;resize:none;"
    "font-family:inherit;line-height:1.4;max-height:9.5rem;overflow-y:hidden}"
    ".fin textarea:focus{outline:none;border-color:#206bc4}"
    ".bsn{background:#206bc4;color:#fff;border:none;border-radius:6px;"
    "padding:0 .88rem;font-size:.78rem;font-weight:600;cursor:pointer;height:2.1rem}"
    ".bsn:hover{background:#1a5aaa}"
    ".emp{display:flex;align-items:center;justify-content:center;height:100%;"
    "color:#4a5568;font-size:.86rem}"
    ".df{background:#3a1f1f;border-left:2px solid #f03e3e;padding:.25rem .4rem;"
    "font-family:monospace;font-size:.73rem;white-space:pre-wrap;word-break:break-all;"
    "border-radius:3px;margin-top:.25rem}"
    ".dn{background:#1f3a1f;border-left:2px solid #51cf66;padding:.25rem .4rem;"
    "font-family:monospace;font-size:.73rem;white-space:pre-wrap;word-break:break-all;"
    "border-radius:3px;margin-top:.18rem}"
    ".bx{padding:.17rem .4rem;font-size:.7rem;border:none;border-radius:4px;"
    "cursor:pointer;font-weight:600;margin-right:.2rem;margin-top:.28rem}"
    ".bx-a{background:#206bc4;color:#fff}.bx-c{background:#862e2e;color:#fff}"
    ".pnl-body{flex:1;overflow-y:auto;overflow-x:auto;padding:.55rem .8rem}"
    ".pnl-body::-webkit-scrollbar{width:4px}"
    ".pnl-body::-webkit-scrollbar-thumb{background:rgba(255,255,255,.15);border-radius:2px}"
    ".tbl{width:100%;border-collapse:collapse;font-size:.81rem}"
    ".tbl th{text-align:left;padding:.3rem .52rem;color:#6b7685;font-weight:600;"
    "font-size:.7rem;text-transform:uppercase;border-bottom:1px solid #2d3748}"
    ".tbl td{padding:.34rem .52rem;border-bottom:1px solid rgba(255,255,255,.04);"
    "color:#d0d7de;vertical-align:middle}"
    ".tbl tr:hover td{background:rgba(255,255,255,.04)}"
    ".pill{display:inline-block;padding:.08rem .36rem;border-radius:8px;"
    "font-size:.64rem;font-weight:700;text-transform:uppercase}"
    ".p-ok{background:#1f3a1f;color:#51cf66}.p-off{background:#2a2a2a;color:#868e96}"
    ".p-mgr{background:#1e3a5f;color:#4da6ff}.p-adm{background:#2a1f5f;color:#9b7aff}"
    ".set-key{font-family:ui-monospace,monospace;font-size:.79rem;color:#4da6ff}"
    ".set-desc{font-size:.71rem;color:#6b7685;margin-top:.1rem}"
    ".set-val{background:#0f1117;border:1px solid #2d3748;border-radius:4px;"
    "color:#d0d7de;padding:.26rem .42rem;font-size:.79rem;font-family:inherit;width:100%}"
    ".set-val:focus{outline:none;border-color:#206bc4}"
    ".frm-ta{width:100%;background:#1a1f2e;border:1px solid #2d3748;border-radius:6px;"
    "color:#d0d7de;padding:.36rem .52rem;font-size:.8rem;resize:vertical;"
    "min-height:7rem;font-family:inherit}"
    ".frm-ta:focus{outline:none;border-color:#206bc4}"
    ".frm-inp{width:100%;background:#1a1f2e;border:1px solid #2d3748;border-radius:6px;"
    "color:#d0d7de;padding:.36rem .52rem;font-size:.8rem;font-family:inherit}"
    ".frm-inp:focus{outline:none;border-color:#206bc4}"
    ".frm-lbl{font-size:.72rem;color:#6b7685;margin-bottom:.15rem;display:block}"
    ".frm-grp{margin-bottom:.45rem}"
    ".btn-sm{padding:.22rem .55rem;font-size:.75rem;border:none;border-radius:4px;"
    "cursor:pointer;font-weight:600}"
    ".btn-p{background:#206bc4;color:#fff}.btn-p:hover{background:#1a5aaa}"
    ".btn-g{background:rgba(255,255,255,.08);color:#d0d7de;border:none;"
    "border-radius:4px;text-decoration:none;font-size:.75rem;padding:.22rem .55rem;"
    "font-weight:600;cursor:pointer}"
    ".btn-g:hover{background:rgba(255,255,255,.14)}"
    ".htmx-indicator{display:none}"
    # SELF-match only. The descendant form (.htmx-request .htmx-indicator) meant ANY ancestor
    # in flight lit up EVERY indicator below it — and htmx.ajax() without a `source` marks
    # <body>, so a thread-list search/filter made the chat's "Stepan is thinking" spinner
    # appear out of nowhere. Every indicator here is pointed at by an explicit hx-indicator,
    # so htmx marks the indicator element itself and nothing needs the descendant match.
    ".htmx-request.htmx-indicator{display:inline-block}"
    ".msg-prev{max-width:220px;max-height:280px;border-radius:8px;display:block;margin-top:.25rem}"
    ".media-load{width:120px;height:90px;margin-top:.25rem;border-radius:8px;"
    "background:#222a38;display:flex;align-items:center;justify-content:center;"
    "color:#6b7685;font-size:1rem}"
    ".mrec{margin-top:.3rem;display:inline-flex;align-items:center;gap:.32rem;"
    "background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.13);"
    "color:#9fb0c4;font-size:.66rem;padding:.2rem .5rem;border-radius:6px;cursor:pointer}"
    ".mrec:hover{background:rgba(255,255,255,.12);color:#e8eef6}"
    ".mrec[disabled]{opacity:.5;cursor:progress}"
    ".mrec-err{margin-top:.25rem;font-size:.66rem;color:#ff8787}"
    ".rcpt{opacity:.55;font-size:.7rem}.rcpt.seen{color:#4da3ff;opacity:.95}"
    ".pres.on{color:#51cf66}.ti-fl{color:#6b7685;font-size:.62rem}"
    ".ti-br{color:#8b98a5;font-size:.6rem;margin-left:.3rem;"
    "background:rgba(255,255,255,.07);border-radius:3px;padding:0 .28rem}"
    ".ti-off{font-size:.62rem;margin-left:.3rem;opacity:.85;filter:grayscale(.3)}"
    ".oq-chat{color:#4da3ff;text-decoration:none;font-family:ui-monospace,monospace;"
    "font-size:.74rem}.oq-chat:hover{text-decoration:underline}"
    ".kdoc{background:#1a1f2e;border:1px solid #2d3748;border-radius:7px;"
    "padding:.5rem .7rem;margin-bottom:.3rem;cursor:pointer}"
    ".kdoc:hover{border-color:#4a5568}"
    ".kdoc-slug{font-family:ui-monospace,monospace;font-size:.7rem;color:#4da6ff;"
    "margin-bottom:.1rem}"
    ".br-badge{display:inline-block;margin-left:.4rem;padding:.03rem .34rem;border-radius:6px;"
    "font-size:.6rem;font-weight:600;background:#26314a;color:#8aa4d6;vertical-align:middle}"
    ".kind-badge{display:inline-block;margin-left:.3rem;padding:.03rem .34rem;border-radius:6px;"
    "font-size:.6rem;font-weight:600;background:#2a2340;color:#c3a6ff;vertical-align:middle}"
    ".kdoc-title{font-weight:600;color:#e8eef4;font-size:.82rem;margin-bottom:.1rem}"
    ".kdoc-preview{font-size:.74rem;color:#6b7685;overflow:hidden;text-overflow:ellipsis;"
    "white-space:nowrap}"
    ".hint{font-size:.74rem;color:#4a5568;padding:.32rem 0 .45rem;line-height:1.45}"
    # ── knowledge-base tree / editor / history ──
    ".kb-tabs{display:flex;gap:.3rem;align-items:center;padding:.4rem .5rem;"
    "border-bottom:1px solid #222836}"
    ".kb-tab{flex:1;background:#161b26;border:1px solid #2d3748;color:#93a1b3;"
    "padding:.3rem;border-radius:5px;font-size:.76rem;cursor:pointer}"
    ".kb-tab.on{background:#206bc4;border-color:#206bc4;color:#fff}"
    ".kb-reix{background:#161b26;border:1px solid #2d3748;color:#93a1b3;border-radius:5px;"
    "padding:.3rem .5rem;cursor:pointer;font-size:.9rem}"
    ".kb-reix:hover{border-color:#4da6ff;color:#4da6ff}"
    ".kb-reix-msg{display:block;font-size:.72rem;color:#5aa2ff;padding:.25rem .6rem}"
    ".kb-grp{margin:.15rem 0}"
    ".kb-grp>summary{cursor:pointer;font-size:.72rem;text-transform:uppercase;"
    "letter-spacing:.04em;color:#6b7685;padding:.3rem .55rem;user-select:none}"
    # outer branch group (only when the KB view spans >1 branch)
    ".kb-branch{margin:.15rem 0;border-left:2px solid #2d3748}"
    ".kb-branch>summary{cursor:pointer;font-size:.74rem;font-weight:700;color:#8aa4d6;"
    "padding:.35rem .55rem;user-select:none;background:#161b26}"
    ".kb-branch .kb-grp{margin-left:.5rem}"
    ".ch-slug{font-family:ui-monospace,monospace;font-size:.72rem;color:#4da6ff;"
    "margin-left:.4rem}"
    ".kb-by{font-size:.7rem;color:#6b7685}"
    # No overflow:hidden here, however much the rounded corners want it: it would make this
    # <details> the containing scroll box for the sticky save bar inside, and a box that never
    # scrolls gives sticky nothing to stick to — the button just sat at its natural offset,
    # 1124px down, exactly as invisible as before. The corners are clipped on the summary
    # instead, which is the only child whose background reaches the border.
    ".kb-doc{border:1px solid var(--line,#2d3748);border-radius:10px;margin-bottom:.6rem}"
    ".kb-doc>summary{border-radius:9px 9px 0 0}"
    ".kb-doc:not([open])>summary{border-radius:9px}"
    ".kb-doc>summary{display:flex;align-items:center;gap:.6rem;padding:.65rem .9rem;"
    "cursor:pointer;list-style:none;background:#141922;user-select:none}"
    ".kb-doc>summary::-webkit-details-marker{display:none}"
    ".kb-doc>summary::before{content:'▸';color:#6b7685;font-size:.8rem}"
    ".kb-doc[open]>summary::before{content:'▾'}"
    ".kb-doc[open]>summary{border-bottom:1px solid var(--line,#2d3748)}"
    ".kb-doc-t{font-weight:600;font-size:.9rem}"
    ".kb-doc-m{margin-left:auto;font-size:.72rem;color:#6b7685;font-family:ui-monospace,"
    "SFMono-Regular,Menlo,monospace}"
    ".kb-doc .ch{border:0;background:transparent}"
    ".kb-doc .ch-n{display:none}"
    # The save button sat under the textarea, and the textarea is sized from the document —
    # facts_policy is 15.7k chars, so 48 rows, so the button was ~1500px below the fold and
    # read as missing. Stuck to the bottom of the scrolling panel instead; the gradient keeps
    # the text from running into it.
    ".kb-save-bar{position:sticky;bottom:0;margin-top:.5rem;padding:.7rem 0 .5rem;"
    "display:flex;align-items:center;gap:.6rem;z-index:5;"
    "background:linear-gradient(to top,#0f1117 65%,rgba(15,17,23,0))}"
    ".kb-save-hint{font-size:.7rem;color:#6b7685}"
    ".kb-sec{margin-bottom:.5rem}"
    ".kb-sec-h{display:block;font-size:.74rem;font-weight:600;color:#9db3c9;"
    "margin-bottom:.15rem}"
    # the whole doc is edited as markdown in one field — monospace keeps ## headings and
    # list indentation readable, and the tab stop stays sane on long facts documents
    ".kb-md{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;"
    "font-size:.8rem;line-height:1.5;tab-size:2}"
    ".kb-tr-note{margin:.6rem 0;padding:.5rem .7rem;font-size:.78rem;color:#8fb6ff;"
    "background:rgba(90,162,255,.08);border:1px solid rgba(90,162,255,.25);border-radius:6px}"
    ".frm-ta[readonly],.frm-inp[readonly]{color:#8fb6ff;background:#161d2b}"
    ".kb-rev{border:1px solid #2d3748;border-radius:6px;margin-bottom:.5rem;overflow:hidden}"
    ".kb-rev-h{display:flex;gap:.6rem;align-items:center;padding:.35rem .55rem;"
    "background:#161b26;font-size:.74rem}"
    ".kb-diff{font-family:ui-monospace,monospace;font-size:.68rem;padding:.3rem .55rem;"
    "max-height:14rem;overflow-y:auto}"
    ".d-add{color:#7ee2a8}.d-del{color:#ff9b9b}.d-ctx{color:#5a6675}"
    # ── captured needs (VPC) box in chat header ──
    ".nd-box{padding:.3rem .7rem;border-top:1px solid #222836;display:flex;"
    "flex-direction:column;gap:.2rem}"
    ".nd-row{display:flex;flex-wrap:wrap;gap:.3rem;align-items:center}"
    ".nd-lbl{font-size:.66rem;color:#6b7685;min-width:3.6rem}"
    ".nd-chip{font-size:.68rem;padding:.08rem .4rem;border-radius:10px;"
    "border:1px solid #2d3748}"
    ".nd-job{background:#12233b;color:#7db8ff}"
    ".nd-pain{background:#301a1a;color:#ffb0a3}"
    ".nd-gain{background:#132a1e;color:#8fe3ac}"
    # ── Stepan on/off switches (platform + branch) ──
    ".tgl-row{margin:.2rem 0}"
    ".tgl-hint{margin:.25rem 0;font-size:.63rem;line-height:1.3;color:#6b7688;font-style:italic}"
    ".tgl-btn{width:100%;display:flex;align-items:center;gap:.4rem;background:#161b26;"
    "border:1px solid #2d3748;border-radius:6px;padding:.32rem .5rem;cursor:pointer}"
    ".tgl-btn:hover{border-color:#3a5578}"
    ".tgl-lbl{flex:1;text-align:left;font-size:.72rem;color:#c3cede}"
    ".tgl-status{font-size:.64rem;font-weight:700;letter-spacing:.03em}"
    ".tgl-track{width:2rem;height:.95rem;border-radius:1rem;position:relative;"
    "flex-shrink:0;transition:background .15s}"
    ".tgl-knob{position:absolute;top:.1rem;left:.1rem;width:.75rem;height:.75rem;"
    "border-radius:50%;background:#fff;transition:transform .15s}"
    ".help-btn{width:1.45rem;height:1.45rem;border-radius:50%;background:#206bc4;"
    "color:#fff;border:none;font-size:.72rem;font-weight:700;cursor:pointer;"
    "flex-shrink:0;line-height:1}"
    # help mode: the ? toggle lights up, every annotated element gets a dashed outline
    # ('hover me'), and one fixed-position tip floats ABOVE the page so card/table
    # overflow can never clip it.
    "body.help-mode .help-btn{background:#e2b33d;color:#1a1f2e}"
    # Help mode lights up EVERY hinted element unmistakably (amber outline + tint + a ? cursor)
    # so it's obvious where to hover; the full text shows on hover in #help-tip.
    "body.help-mode [data-help]{outline:2px solid rgba(226,179,61,.85);outline-offset:1px;"
    "background:rgba(226,179,61,.10);border-radius:4px;cursor:help}"
    "body.help-mode [data-help]:hover{background:rgba(226,179,61,.22);"
    "outline-color:#e2b33d}"
    "#help-tip{position:fixed;z-index:900;max-width:300px;background:#1b2432;"
    "border:1px solid #3a5578;border-radius:8px;padding:.5rem .7rem;font-size:.78rem;"
    "color:#cfe0f4;line-height:1.5;box-shadow:0 6px 24px rgba(0,0,0,.55);display:none;"
    "pointer-events:none}"
    # chat actions
    ".ch-acts{display:flex;align-items:center;gap:.4rem;margin-left:auto}"
    ".act-sel{background:#1a1f2e;border:1px solid #2d3748;border-radius:5px;"
    "color:#d0d7de;font-size:.74rem;padding:.18rem .35rem;cursor:pointer}"
    ".act-sel:focus{outline:none;border-color:#206bc4}"
    ".act-btn{background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.12);"
    "border-radius:5px;color:#8899aa;font-size:.72rem;padding:.18rem .45rem;"
    "cursor:pointer;white-space:nowrap}"
    ".act-btn:hover{background:rgba(32,107,196,.28);color:#4da6ff;border-color:#206bc4}"
    ".act-btn.primary{background:#206bc4;color:#fff;border-color:#206bc4}"
    ".act-btn.primary:hover{background:#1a5aaa}"
    # two-position bot toggle (OFF | ON) — sliding knob
    ".bot-tog{position:relative;display:inline-flex;align-items:center;background:#12161f;"
    "border:1px solid #2d3748;border-radius:999px;padding:2px;cursor:pointer;font-size:.66rem;"
    "font-weight:700;line-height:1;letter-spacing:.04em;user-select:none}"
    ".bot-tog .seg{position:relative;z-index:1;padding:.22rem .5rem;border-radius:999px;"
    "color:#6b7685;transition:color .2s}"
    ".bot-tog .knob{position:absolute;top:2px;bottom:2px;width:calc(50% - 2px);border-radius:999px;"
    "transition:left .2s ease,background .2s;z-index:0}"
    ".bot-tog.off .knob{left:2px;background:#ff6b6b}"
    ".bot-tog.on .knob{left:calc(50% - 0px);background:#51cf66}"
    ".bot-tog.off .seg.off{color:#1a0808}"
    ".bot-tog.on .seg.on{color:#08160a}"
    ".bot-tog:hover{border-color:#3a4759}"
    # suggest box
    ".sug-box{padding:.45rem .75rem;background:#1a1f2e;border-top:1px solid #2d3748;"
    "display:flex;flex-direction:column;gap:.3rem;flex-shrink:0}"
    ".sug-ta{width:100%;background:#0f1117;border:1px solid #2d3748;border-radius:5px;"
    "color:#d0d7de;padding:.3rem .45rem;font-size:.79rem;resize:vertical;"
    "min-height:3.5rem;font-family:inherit;line-height:1.4}"
    ".sug-ta:focus{outline:none;border-color:#206bc4}"
    ".sug-acts{display:flex;gap:.4rem}"
    # lead/outbox tables
    ".st-pill{display:inline-block;padding:.06rem .28rem;border-radius:5px;"
    "font-size:.62rem;font-weight:700;text-transform:uppercase}"
    ".s-pend{background:#2a2218;color:#ffd43b}"
    ".s-sent{background:#1f3a1f;color:#51cf66}"
    ".s-fail{background:#3a1f1f;color:#ff6b6b}"
    # mobile floating bar (hidden on desktop)
    ".mbar{display:none}"
    ".mbtn{position:fixed;top:.5rem;z-index:70;width:2.2rem;height:2.2rem;border:none;"
    "border-radius:50%;background:#206bc4;color:#fff;font-size:1.2rem;line-height:1;"
    "box-shadow:0 2px 8px rgba(0,0,0,.4);cursor:pointer}"
    ".mnav{left:.5rem}.mback{left:.5rem;display:none}"
    # ── responsive: phones/tablets (all desktop CSS above is untouched) ──
    # ── the gap between the phone layout and a comfortable desktop ──────────────
    # Above 760px the three columns return at full width and none of them can shrink:
    # sidebar 210 + thread list 305 + two 4px resize handles = 523px of fixed chrome, which
    # leaves a 768px tablet 245px of chat. Only the THREAD LIST narrows here.
    #
    # The sidebar deliberately does not: collapsing it to icons hides .sid-ft, and that is
    # where the branch picker, the bot/sending/comment switches and the language buttons live.
    # Shipped as an auto-collapse on 2026-07-28 and reverted the same day — the first person to
    # open the panel on a phone could not find the switches, and no width is a good enough
    # reason to take controls away from someone who did not ask. The manual collapse stays; it
    # is a choice, made with a visible button to undo it.
    "@media (min-width:761px) and (max-width:1150px){"
    ".thr{width:248px}"
    "}"
    "@media (max-width:760px){"
    "body{padding-top:0}"
    ".mbar{display:block}"
    # sidebar becomes a slide-in overlay, opened by the ☰ button
    ".sid{position:fixed;left:0;top:0;bottom:0;z-index:80;transform:translateX(-100%);"
    "transition:transform .2s ease;box-shadow:2px 0 12px rgba(0,0,0,.5)}"
    "body.nav-open .sid{transform:translateX(0)}"
    ".sbrz,.thrz{display:none}"
    # thread list is the default full-width mobile view
    ".thr{width:auto;flex:1;padding-top:2.9rem}"
    # #main (a chat) slides in over the thread list; back button reveals the list again
    "#main{position:fixed;inset:0;z-index:60;background:#0f1117;transform:translateX(100%);"
    "transition:transform .2s ease}"
    "body.chat-open #main{transform:translateX(0)}"
    "body.chat-open .mnav{display:none}body.chat-open .mback{display:block}"
    # the fixed ‹ back button sits top-left over #main — pad the header so it does not
    # cover the lead avatar
    "body.chat-open .ch{padding-left:2.9rem}"
    # touch has no hover: keep the per-message translate/delete buttons visible
    ".trx,.delx{opacity:.5}"
    # give tables room to scroll horizontally instead of overflowing the viewport
    ".tbl{min-width:520px}"
    "}"
)
