ALTER TABLE lead ADD COLUMN IF NOT EXISTS ig_username VARCHAR;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS ig_user_id VARCHAR;
ALTER TABLE lead ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE channel_thread ADD COLUMN IF NOT EXISTS lead_source VARCHAR(40);
ALTER TABLE channel_thread ADD COLUMN IF NOT EXISTS ad_id VARCHAR(40);
ALTER TABLE channel_thread ADD COLUMN IF NOT EXISTS ad_media_id VARCHAR(40);
ALTER TABLE channel_thread ADD COLUMN IF NOT EXISTS ad_preview_url TEXT;
