"""init schema

Revision ID: 5ff069fc75d8
Revises: 
Create Date: 2026-06-28 19:06:47.530848
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5ff069fc75d8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_telegram_id'), 'app_user', ['telegram_id'], unique=True)
    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('tz_offset_h', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'key', name='uq_setting_branch_key')
    )
    op.create_index(op.f('ix_app_setting_branch_id'), 'app_setting', ['branch_id'], unique=False)
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_branch_id'), 'channel', ['branch_id'], unique=False)
    op.create_table('knowledge_doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'slug', name='uq_kdoc_branch_slug')
    )
    op.create_index(op.f('ix_knowledge_doc_branch_id'), 'knowledge_doc', ['branch_id'], unique=False)
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('phone_e164', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('ready_subtype', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_branch_id'), 'lead', ['branch_id'], unique=False)
    op.create_index(op.f('ix_lead_phone_e164'), 'lead', ['phone_e164'], unique=False)
    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_branch_id'), 'membership', ['branch_id'], unique=False)
    op.create_index(op.f('ix_membership_user_id'), 'membership', ['user_id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'slug', name='uq_product_branch_slug')
    )
    op.create_index(op.f('ix_product_branch_id'), 'product', ['branch_id'], unique=False)
    op.create_table('channel_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('secret_enc', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_ok_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_session_channel_id'), 'channel_session', ['channel_id'], unique=False)
    op.create_table('channel_thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('external_thread_id', sa.String(), nullable=False),
    sa.Column('product_slug', sa.String(), nullable=True),
    sa.Column('window_until', sa.DateTime(), nullable=True),
    sa.Column('last_in_at', sa.DateTime(), nullable=True),
    sa.Column('last_out_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_thread_channel_id'), 'channel_thread', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_thread_external_thread_id'), 'channel_thread', ['external_thread_id'], unique=False)
    op.create_index(op.f('ix_channel_thread_lead_id'), 'channel_thread', ['lead_id'], unique=False)
    op.create_table('manager_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('lead_phone', sa.String(), nullable=True),
    sa.Column('summary_en', sa.String(), nullable=False),
    sa.Column('summary_ru', sa.String(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['channel_thread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manager_alert_branch_id'), 'manager_alert', ['branch_id'], unique=False)
    op.create_index(op.f('ix_manager_alert_lead_id'), 'manager_alert', ['lead_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('sent_by', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['channel_thread.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'external_id', name='uq_msg_ext')
    )
    op.create_index(op.f('ix_message_branch_id'), 'message', ['branch_id'], unique=False)
    op.create_index(op.f('ix_message_thread_id'), 'message', ['thread_id'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['channel_thread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_branch_id'), 'outbox', ['branch_id'], unique=False)
    op.create_index(op.f('ix_outbox_status'), 'outbox', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_thread_id'), 'outbox', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_thread_id'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_status'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_branch_id'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_message_thread_id'), table_name='message')
    op.drop_index(op.f('ix_message_branch_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_manager_alert_lead_id'), table_name='manager_alert')
    op.drop_index(op.f('ix_manager_alert_branch_id'), table_name='manager_alert')
    op.drop_table('manager_alert')
    op.drop_index(op.f('ix_channel_thread_lead_id'), table_name='channel_thread')
    op.drop_index(op.f('ix_channel_thread_external_thread_id'), table_name='channel_thread')
    op.drop_index(op.f('ix_channel_thread_channel_id'), table_name='channel_thread')
    op.drop_table('channel_thread')
    op.drop_index(op.f('ix_channel_session_channel_id'), table_name='channel_session')
    op.drop_table('channel_session')
    op.drop_index(op.f('ix_product_branch_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_membership_user_id'), table_name='membership')
    op.drop_index(op.f('ix_membership_branch_id'), table_name='membership')
    op.drop_table('membership')
    op.drop_index(op.f('ix_lead_phone_e164'), table_name='lead')
    op.drop_index(op.f('ix_lead_branch_id'), table_name='lead')
    op.drop_table('lead')
    op.drop_index(op.f('ix_knowledge_doc_branch_id'), table_name='knowledge_doc')
    op.drop_table('knowledge_doc')
    op.drop_index(op.f('ix_channel_branch_id'), table_name='channel')
    op.drop_table('channel')
    op.drop_index(op.f('ix_app_setting_branch_id'), table_name='app_setting')
    op.drop_table('app_setting')
    op.drop_table('branch')
    op.drop_index(op.f('ix_app_user_telegram_id'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
